version: 2.1

workflows:
  workflow:
    jobs:
      - build:
          context: soluble-example-org

jobs:
  build:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - checkout
      - run: "curl -sL https://raw.githubusercontent.com/soluble-ai/soluble-cli/master/linux-install.sh | sh"
      - run: "soluble tf-scan tfsec -d terraform/aws --upload"
      - run: "soluble tf-scan checkov -d terraform/aws --upload  --filter check_result=FAILED --error-not-empty"
      - run: "soluble secrets-scan --upload"
